version: "3"

services:
  database:
    container_name: mysql
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      - nodesql
  api:
    container_name: api
    build:
      context: node
    entrypoint: bash -c "npm install && wait-for mysql:3306 -t 40 -- node index.js"
    command:
    volumes:
      - ./node/src:/app
    networks:
      - nodesql
    tty: true
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: nginx
    networks:
      - nodesql
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  nodesql:
    driver: bridge
